# Render.com Configuration for Thai Document Generator
# Free tier deployment configuration

services:
  - type: web
    name: thai-document-generator
    env: docker
    dockerfilePath: ./Dockerfile
    
    # Free tier resource limits
    # Render free tier: 512MB RAM, 0.1 CPU, 1GB storage
    plan: free
    
    # Health check configuration
    healthCheckPath: /api/health
    
    # Auto-deploy from main branch
    autoDeploy: true
    branch: main
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOSTNAME
        value: 0.0.0.0
      
      # These should be set as secrets in Render dashboard:
      - key: MFEC_LLM_BASE_URL
        sync: false  # Set as secret
      - key: MFEC_LLM_API_KEY
        sync: false  # Set as secret
      - key: MFEC_LLM_CHAT_MODEL
        sync: false  # Set as secret
      - key: MFEC_LLM_EMBEDDING_MODEL
        sync: false  # Set as secret
      - key: ENCRYPTION_KEY
        sync: false  # Set as secret
      - key: NEXT_PUBLIC_APP_URL
        sync: false  # Set as secret
      - key: ALLOW_USER_API_KEYS
        value: "true"
      
      # Free tier logging configuration
      - key: LOG_LEVEL
        value: "info"
      - key: DEBUG_MODE
        value: "false"
    
    # Disk storage for exports (free tier limit: 1GB)
    disk:
      name: exports
      mountPath: /app/exports
      sizeGB: 1
    
    # Build configuration
    buildCommand: echo "Using Dockerfile for build"
    startCommand: node server.js